export enum Gender {
    MALE="Male",
    FEMALE="Female"
}
export enum Type_Time{
    PARTTIME="Partime",
    FULLTIME="FullTime",
    HYBRID="Hybrid"
}
export enum Status{
    Active="Active",
    InActive="InActive"

}
export enum Designation{
    TRAINEE="TRAINEE",
    JUNIOR_SOFTWARE_ENGINEER="JUNIOR_SOFTWARE_ENGINEER",
    SOFTWARE_ENGINEER="SOFTWARE_ENGINEER",
    SENIOR_SOFTWARE_ENGINEER="SENIOR_SOFTWARE_ENGINEER",
    TECHNICAL_LEAD="TECHNICAL_LEAD"
}
export enum Blood_Group{
    AB_POSITIVE="AB+",
    AB_NEGATIVE="AB-",
    A_POSITIVE="A+",
    A_NEGATIVE="A-",
    B_POSITIVE="B",
    B_NEGATIVE="B-",
    O_POSITIVE="O+",
    O_NEGATIVE="O-"
}
export enum Documents{
    SSC="10th MARKSHEETS",
    HSC="12th MARKSHEETS",
    RESUME="RESUME",
    JOINING_LETTER="JOINING LETTER",
    TRAINING_CERTIFICATE="TRAINING CERTIFICATE",
    AADHAAR_CARD="AADHAAR CARD",
    PAN_CARD="PAN CARD",
    OFFER_LETTER="OFFER LETTER",
    RELIVING_LETTER="RELIEVING LETTER",
    EXPERIENCE_LETTER="EXPERIENCE LETTER",
    PASSPORT_PHOTO="PASSPORT PHOTO",
    BIRTHDAY_PHOTO="BIRTHDAY PHOTO",
    SIGNATURE_PHOTO="SIGNATURE PHOTO",
    APPOINTMENT_LETTER="APPOINTMENT LETTER",
    AGREEMENT_LETTER="AGREEMENT LETTER"
}