import AboutUs from "./company/aboutUs";
import Anniversary from './events/anniversary/anniversary';
import Birthday from './events/birthday/birthday';
import ContactUs from "./company/contactUs";
import EmployeeCreate from "./employee/employeeCreate/employeeCreate";
import EmployeeDetailComponent02 from './employee/employeeDetail/employeeDetail02';
import EmployeeSearch from './employee/employeeSearch';
import EnumCards from "./enums/enum-detail/enum-cards";
import Error from "./error page/error";
import ForgotPassword from './forgotPassword/forgotPassword';
import HolidayCalendar from './holiday/calendar';
import HolidayCreate from './holiday/holidayCreate';
import HolidayList from './holiday/holidayList';
import Home from "../component/home/home";
import Login from "./login/login";
import LayoutComponent from './layoutComponent/layoutComponent';
import PrivacyPolicy from "./company/privacyPolicy";
import PrivateRoutes from '../privateRoutes/privateRoutes';
import UserCreate from "./user/user-create/userCreate";
import UserDataTable from "./user/user-list/userDataTable";
import UserDetailsCard from "./user/user-cards/userDetailsCard";
import Leaves from "./leave/leaves";

export { AboutUs, Anniversary, Birthday, ContactUs, EmployeeCreate, EmployeeDetailComponent02, EmployeeSearch, EnumCards, Error, ForgotPassword,HolidayCalendar,HolidayCreate,HolidayList, Home,LayoutComponent, Login,  PrivacyPolicy,PrivateRoutes, UserCreate,UserDataTable, UserDetailsCard, Leaves  };
